theme = "rose_pine_dawn"

[editor]
line-number  = "relative"
mouse        = true
true-color   = true
cursorline   = true
cursorcolumn = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL "
mode.insert = "INSERT "
mode.select = "SELECT "

[keys.insert]
j = { j = "normal_mode" }
